### PR TITLE
850 add user strategy to summary

### PR DESCRIPTION
**Pull request by Jonathanko52**
#850 User strategy entered on 4th page now appears on 5th(Summary) page.
Screen Shot 2021-08-05 at 6 01 17 PM

### CODE REVIEW

**Review by nclairesays — CHANGES_REQUESTED** [review]
@Jonathanko52 
- The only time a user would write a description in the user defined strategy (going to use UDS) is if they write in their own points for that field. It doesn't make sense to have a specific section for just  UDS.
image

image

Instead, it should be under Project Measures.

image

-------------

Something else I noticed that should have been added to this issue is to include the points for the UDS too.  Please add the points similar to how the "start a new TMO" "join TMO" and then have  the UDS's description below that.

**Comment by KPHowley** [comment]
Hi @Jonathanko52  -  I am going to push this back into progress, and we should make the changes according to Claires comments!

**Comment by Jonathanko52** [comment]
Screen Shot 2021-09-01 at 9 26 12 PM
Border, margins changed. Please let me know if this is closer to what you had in mind.

**Comment by Shaeeka** [comment]
Hey John,
You are close, I have attached the screenshot with the figma link in #850
and #873. The width of the summary section in the figma is smaller than the
webpage. I would prefer the border of the text frame to be shade of grey
E7EBF0 and remove the indentation keeping it parallel to the header. If you
need more explanations please feel free to slack me.
[image: image.png]

Thanks,
Shaeeka

**Comment by Jonathanko52** [comment]
Requested changes made.

**Pull request merged**
