### PR TITLE
Adds Server Side Validation to Schema's

### PR DESCRIPTION
**Pull request by azajzon**
Addresses #1360 

Changes Made:

Added RegEx for server-side validation to reduce bad actor attempts across various fields on the TDM website

### CODE REVIEW

**Comment by azajzon** [comment]
if possible we can link Alejandro's pull request with this one

**Comment by agosmou** [comment]
For discussion on Wednesday

https://github.com/hackforla/tdm-calculator/commit/70ca7db82ab2f1fe687c55d15dcaa3853e4d1e69

**Comment by agosmou** [comment]
> if possible we can link Alejandro's pull request with this one
[Original commit](https://github.com/hackforla/tdm-calculator/commit/70ca7db82ab2f1fe687c55d15dcaa3853e4d1e69) should be discarded

I've pushed changes from Abel's branch, so this PR is now up to date with changes from Abel and my branches.

**Comment by agosmou** [comment]
@entrotech 

We can review this during our call to see if we remove the extra changes unrelated to this PR, e.g. the package-lock file and the removal of lerna

**Pull request merged**
