### PR TITLE
Update Navbar to display current page via color change

### PR DESCRIPTION
**Pull request by alexchoiweb**
-Added color indicator for current page on navbar
-Added hover effect for nav links

I'm still fairly new to making pull requests so please let me know if there's anything else you need.

Issue:
https://github.com/hackforla/tdm-calculator/issues/395

### CODE REVIEW

**Comment by alexchoiweb** [comment]
@nclairesays @KPHowley
All changes made
One last thing - What did we decide on for the behavior of "My Projects" link? Always white, and unable to be interacted with if user is logged out?

**Comment by KPHowley** [comment]
@alexchoiweb - for now just keep my projects page visibility as it was, where it is only visible when a user is logged in. We want to do some testing and then will create an issue if necessary.

**Comment by alexchoiweb** [comment]
@KPHowley 

All changed made, let me know if anything is missing
https://streamable.com/rhmsf3

**Comment by KPHowley** [comment]
@alexchoiweb - hey everything looks good visually to me, @nclairesays  are you able to review the commit?

**Comment by nclairesays** [comment]
I can review it later tonight

**Comment by nclairesays** [comment]
@alexchoiweb I don't see the updated changes on this PR or your branch. Can you push that up? Also, make sure to resolve any merge conflicts, if any. Here are the steps on how you can use git rebase (what I wanted to show you last week).
1. `git checkout develop`
2. `git pull -r` (so that you can have the most updated changes)
3. `git checkout alex-navbar` (or whatever branch you're on)
4. `git rebase develop` (this puts your commits from your branch on top of any commits that were on the develop branch)
5. resolve conflicts, if any. most likely won't have any/many if you choose to use rebase (instead of merge). however, _if_ there happen to be any conflicts, resolve them and type `git rebase --continue`
6. `git push` (push your changes to your branch. it will automatically include them on this pull request)
(If you need assistance, message me on slack.)

**Comment by nclairesays** [comment]
Per a separate convo with alex on slack, we are working together to fix this branch.

**Pull request merged**
