### PR TITLE
881 876 869 rules sqft number of alternative

### LINKED ISSUE #869: Change "Version #" to "Alternative #"
### Overview
Based on the usability testing (row 8), users are unclear what "Version #" means. Let's change "Version #" to "Alternative #"  

### Action Items

- [x] Change Version # to Alternative #

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

### LINKED ISSUE #876: "# Habitable Rooms" is unclear. The use of numerical notation is confusing
### Overview
User are confused with "# Habitable Rooms" and "Condo - Units"

### Action Items

- [x] Replace "#" with "Number of" for Habitable rooms and Guest rooms
- [x] Add "Number of" in front of Condo-Units

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

### LINKED ISSUE #881: Delete the left "Sq Ft" from Page 2
### Overview
Delete left "Sq Ft" from page 2 as its confusing users. 

### Action Items
Delete the left "Sq Ft" from page 2

### Resources/Instructions
https://docs.google.com/spreadsheets/d/1SEd8uPOwOmEMdsDR_pylZ2tiByopzPrmlqB5Y4Ka4xc/edit?usp=sharing

### LINKED ISSUE #887: Add the following tool tip to Version#/Alternative #
### Overview
Need to add a tooltip to Alternative#/Version# to make it clear to the user what the function of this data. 

### Action Items

- [x] Add tooltip - "This helps distinguish different alternatives/scenarios for the same project."

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

### PR DESCRIPTION
**Pull request by fyliu**
Added DB migration file to do the following:

Remove Sq Ft from page 2
Closes #881 

Change # to Number of in page 2
Closes #876 

Change Version # to Alternative # 
Closes #869 

Add  #tooltip to Alternative #
Closes #887

### CODE REVIEW

**Comment by fyliu** [comment]
Screenshot from 2021-07-28 15-59-07 cropped
above: "Version #" is now "Alternative #", and new tooltip

2021-07-28 15 59 45 localhost 7e7c7a889b78
above: "# of" is now Number of. "Sqft - " is removed from the names on the left.

**Review by nclairesays — CHANGES_REQUESTED** [review]
Missing "Number of Condo - Units" for issue #876

**Comment by fyliu** [comment]
Added missing change.
2021-07-28 19 55 06 localhost 692c422c2921

**Comment by nclairesays** [comment]
I've run migrations on the dev database, but not prod database.

**Pull request merged**
